// \{[\s\n\r]*name:[\n\r\s]*"(.*)"[\n\r\s]*,[\n\r\s]*value:[\n\r\s]*(.*)[\n\r\s]*\}
import globalColors from "./globalColors";
export const figmaAliasLight = {
  bg: {
    default: "gray.50",
    strong: "white",
    weak: "gray.100",
    weakest: "gray.200",
    emphasis: "gray.900/0.8",
    tint: {
      default: "white/0.00001",
      hover: "rgba(18, 30, 48, 0.06)",
      pressed: "rgba(18, 30, 48, 0.12)",
      selected: {
        default: "mint.500/0.16",
        hover: "mint.500/0.24",
      },
      onColor: {
        hover: "white/0.16",
        pressed: "white/0.24",
      },
    },
    success: {
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
      container: "green.100",
    },
    error: {
      default: "red.500",
      container: "red.100",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
    },
    warning: {
      default: "yellow.500",
      container: "yellow.100",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
    },
    primary: {
      default: "mint.500",
      container: "mint.100",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
    },
    new: {
      default: "purple.500",
      container: "purple.100",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
    },
    info: {
      default: "blue.500",
      container: "blue.100",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
    },
    neutral: {
      default: "gray.500",
      container: "gray.100",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
    },
  },
  fg: {
    strong: "gray.900",
    default: "gray.800",
    secondary: "gray.500",
    weak: "gray.400",
    weakest: "gray.300",
    disabled: "gray.200",
    onColor: {
      default: "white",
      disabled: "white/0.24",
    },
    success: {
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
      onContainer: "green.900",
    },
    error: {
      default: "red.500",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
      onContainer: "red.900",
    },
    warning: {
      default: "yellow.500",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
      onContainer: "yellow.900",
    },
    primary: {
      default: "mint.500",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
      onContainer: "mint.900",
    },
    new: {
      default: "purple.500",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
      onContainer: "purple.900",
    },
    info: {
      default: "blue.500",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
      onContainer: "blue.900",
    },
    neutral: {
      default: "gray.500",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
      onContainer: "gray.900",
    },
  },
  border: {
    default: "gray.200",
    divider: "gray.200",
    actionable: "gray.300",
    modal: "black/0.16",
    success: {
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
    },
    error: {
      default: "red.500",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
    },
    warning: {
      default: "yellow.500",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
    },
    primary: {
      default: "mint.500",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
    },
    new: {
      default: "purple.500",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
    },
    info: {
      default: "blue.500",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
    },
    neutral: {
      default: "gray.500",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
    },
  },
};

