// \{[\s\n\r]*name:[\n\r\s]*"(.*)"[\n\r\s]*,[\n\r\s]*value:[\n\r\s]*(.*)[\n\r\s]*\}
import globalColors from "./globalColors";
export const figmaAliasLight = {
  bg: {
    default: "gray.50",
    surface: "white",
    subtle: "gray.100",
    emphasis: "gray.900/0.8",
    overlay: "gray.900/0.2",
    backdrop: "gray.900/0.6",
    action: {
      default: "transparent",
      hover: "gray.900/0.04",
      pressed: "gray.900/0.06",
      selected: {
        default: "mint.500/0.16",
        hover: "mint.500/0.24",
      },
      onColor: {
        hover: "white/0.16",
        pressed: "white/0.24",
      },
    },
    success: {
      subtle: "green.100",
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
    },
    error: {
      subtle: "red.100",
      default: "red.500",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
    },
    warning: {
      subtle: "yellow.100",
      default: "yellow.500",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
    },
    primary: {
      subtle: "mint.100",
      default: "mint.500",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
    },
    new: {
      subtle: "purple.100",
      default: "purple.500",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
    },
    info: {
      subtle: "blue.100",
      default: "blue.500",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
    },
    neutral: {
      subtle: "gray.100",
      default: "gray.500",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
    },
  },
  fg: {
    strong: "gray.900",
    default: "gray.800",
    secondary: "gray.500",
    tertiary: "gray.400",
    subtle: "gray.300",
    disabled: "gray.200",
    onColor: {
      default: "white",
      disabled: "white/0.24",
    },
    success: {
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
      strong: "green.900",
    },
    error: {
      default: "red.500",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
      strong: "red.900",
    },
    warning: {
      default: "yellow.500",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
      strong: "yellow.900",
    },
    primary: {
      default: "mint.500",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
      strong: "mint.900",
    },
    new: {
      default: "purple.500",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
      strong: "purple.900",
    },
    info: {
      default: "blue.500",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
      strong: "blue.900",
    },
    neutral: {
      default: "gray.500",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
      strong: "gray.900",
    },
  },
  border: {
    action: "gray.300",
    default: "gray.200",
    divider: "gray.200",
    modal: "black/0.16",
    success: {
      default: "green.500",
      hover: "green.400",
      pressed: "green.600",
      disabled: "green.200",
    },
    error: {
      default: "red.500",
      hover: "red.400",
      pressed: "red.600",
      disabled: "red.200",
    },
    warning: {
      default: "yellow.500",
      hover: "yellow.400",
      pressed: "yellow.600",
      disabled: "yellow.200",
    },
    primary: {
      default: "mint.500",
      hover: "mint.400",
      pressed: "mint.600",
      disabled: "mint.200",
    },
    new: {
      default: "purple.500",
      hover: "purple.400",
      pressed: "purple.600",
      disabled: "purple.200",
    },
    info: {
      default: "blue.500",
      hover: "blue.400",
      pressed: "blue.600",
      disabled: "blue.200",
    },
    neutral: {
      default: "gray.500",
      hover: "gray.400",
      pressed: "gray.600",
      disabled: "gray.200",
    },
  },
};

